### ISSUE TITLE
bug: user can still access cart page when logged out

### ISSUE THREAD

**Issue by theodevoid** [theodevoid/mikrommerce#13]
### Provide environment information

development and staging

### Describe the bug

User can still access the cart page even when they are currently not logged in.

### Link to reproduction

https://mikrommerce.vercel.app/cart

### To reproduce

- login to app
- go to cart
- logout

**Comment by iasadk** [comment]
I would like to work on this issue can you please assign this to me ??

**Comment by theodevoid** [comment]
> I would like to work on this issue can you please assign this to me ??

Sure!
